alias c='clear'
alias lh='ls -a'
alias ..='cd ..'
alias cd..='cd ..'
alias sha='openssl sha'
alias sha1='openssl sha1'
alias sha256='openssl sha256'
alias sha512='openssl sha512'
alias md5='open md5'
alias mkdir='mkdir -pv'
alias path='echo -e ${PATH//:/\\n}'
alias now='date +"%T"'
alias ping='ping -c 5'
if [ $UID -ne 0 ]; then
	alias reboot='sudo reboot'
	alias shutdown='sudo shutdown'
	alias update='sudo apt-get update'
	alias upgrade='sudo apt-get upgrade'
fi

# aliases for git command
alias gco='git checkout'
alias gcm='git commit'
alias gst='git status'
alias gps='git push'
alias gpl='git pull'
alias glg='git log'
alias ggp='git log --pretty=format:"%h %ad | %s%d [%an]" --graph --date=short'
