alias c='clear'
alias lh='ls -a'
alias ..='cd ..'
alias cd..='cd ..'
alias sha='openssl sha'
alias sha1='openssl sha1'
alias sha256='openssl sha256'
alias sha512='openssl sha512'
alias md5='open md5'
alias mkdir='mkdir -pv'
alias path='echo -e ${PATH//:/\\n}'
alias now='date +"%T"'
alias ping='ping -c 5'
if [ $UID -ne 0 ]; then
	alias reboot='sudo reboot'
	alias shutdown='sudo shutdown'
	alias update='sudo apt-get update'
	alias upgrade='sudo apt-get upgrade'
fi
